# basic params
global_frame: map
robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 5.0

# map
rolling_window: true
width: 10.0
height: 10.0
resolution: 0.01

# obstacles
obstacle_range: 5
max_obstacle_height: 5.0
obstacle_range: 10.0
raytrace_range: 15

# example of the robot footprint
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
footprint_padding: 0.1

# plugins
plugins:
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}


# inflation and threshold under the inflation layer namespace
inflation_layer:
  inflation_radius: 0.05
  cost_scaling_factor: 5.0

# PointCloud2 data source under the obstacle layer namespace
obstacle_layer:
  enabled: true
  observation_sources: point_cloud_sensor
  point_cloud_sensor: 
    sensor_frame: cam_2_color_optical_frame
    data_type: PointCloud2
    topic: /cam_2/depth/color/points
    marking: true
    clearing: true
    max_obstacle_height: 5.0
    min_obstacle_height: 0.01
track_unknown_space: true


